version: '3'

services:
    api:
        image: annaworks/surubot:latest
        env_file:
            - .env
        build: 
            context: ./
            dockerfile: Dockerfile
            args: 
                PORT: "${API_PORT}"
        ports: 
            - "${API_PORT}:${API_PORT}"
        environment:
            API_PORT: "${API_PORT}"
            SLACK_TOKEN: "${SLACK_TOKEN}"

    es: 
        image: docker.elastic.co/elasticsearch/elasticsearch:7.9.0
        volumes:
            - esdata:/usr/share/elasticsearch/data
        environment:
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
            - discovery.type=single-node
        ports: 
            - "9200:9200"

volumes:
    esdata: